# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-22 14:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_page', models.CharField(blank=True, max_length=200, unique=True, verbose_name='Заголовок страницы (Title)')),
                ('title_post', models.CharField(max_length=200, unique=True, verbose_name='Заголовок статьи (h1)')),
                ('status', models.CharField(choices=[('u', 'Unpublished'), ('p', 'Published')], max_length=1)),
                ('text', models.TextField()),
                ('posted', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата публикации')),
                ('description', models.CharField(max_length=200, verbose_name='Description')),
                ('keywords', models.CharField(max_length=200, verbose_name='Keywords')),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Посты',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True, verbose_name='Название тега')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='URL')),
                ('description', models.CharField(max_length=200, verbose_name='Description')),
                ('keywords', models.CharField(max_length=200, verbose_name='Keywords')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(to='blog.Tag', verbose_name='Теги'),
        ),
        migrations.AddField(
            model_name='post',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
