# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-23 14:02
from __future__ import unicode_literals

from django.db import migrations
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20161122_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=model_utils.fields.StatusField(choices=[(0, 'dummy')], default='draft', max_length=100, no_check_for_status=True),
        ),
    ]
