# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-23 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название тега'),
        ),
    ]
