# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-23 14:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20161123_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title_page',
            field=models.CharField(blank=True, max_length=200, verbose_name='Заголовок страницы (Title)'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='title',
            field=models.CharField(max_length=200, unique=True, verbose_name='Название тега'),
        ),
    ]
