# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-06 16:05
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20161201_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='preview',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Превью'),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Полная статья'),
        ),
    ]
