# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-06 16:11
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20161206_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='preview',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Превью'),
        ),
    ]
